sample_string = "something something æøå"
sample_int = 9876
int_arr = [1,2,3]
float_arr = [0.25, 1.3334, 1.0]
string_arr = ["a", "b", "c"]
col = "ff9900"

[table]
my_str = "table.my_str"
my_strings = ["a", "b", "c", "d"]

[my_table]
yes = true
vectors = [
	[1,2],
	[2,4],
]

[my_table.abc]
thomas = "viktil"

[game_config]
board_size            = [8, 8] # dimension of the board in tiles
start_cards           = 7       # number of cards each player starts with
start_cash            = 25000   # amount of cash each player starts with

# styling
player_colors = ["45FFA6", "45B1FF", "A245FF", "FF4588", "FF7245", "FFD645"]

board_tiles = [
	0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,
	0,0,0,0,0,0,0,0,
]

[opponent.1]
id = "archie"
script = "res://scripts/opponents/archie.gd"

[opponent.2]
id = "jacqueline"
script = "res://scripts/opponents/jacqueline.gd"
