[audio]
volume_master = 0
volume_sfx = 0
volume_music = 0

[display]
fullscreen = false

[gameplay]
default_moves = 10
default_gravel_per_tile = 1

[map]
map_cols = 9
map_rows = 12
map_tile_size = 1.0

[levels]

# Resources
# level       1            5                   10                  15               20               25             30                 35                 40
coal       = [2, 3, 4,  3,  6,  5,  6,  7,  2,  1,  0,  4,  5,  2,  3,  3, 2, 2, 4, 6, 8, 10, 10, 8, 6, 4, 4, 6, 6, 8, 10, 12, 14, 16, 18, 20, 10, 8, 12, 14]
copper     = [0, 0, 0,  1,  2,  1,  2,  1,  4,  6,  2,  0,  0,  0,  1,  0, 6, 7, 8, 4, 2,  1,  1, 2, 4, 2, 7, 5, 5, 8,  0,  1,  1,  1,  0,  3,  4, 3,  6,  7]
gold       = [0, 0, 0,  0,  0,  0,  0,  0,  0,  1,  1,  2,  1,  3,  1,  2, 0, 0, 4, 3, 0,  1,  2, 4, 2, 1, 0, 1, 3, 5,  7,  5,  3,  1,  3,  1,  0, 2,  3,  4]

# Monsters
# level       1            5                   10                  15               20               25             30                 35                 40
spider     = [0, 1, 1,  0,  1,  2,  4,  4,  3,  5,  4,  4,  5,  5,  0,  0, 0, 0, 0, 0, 0,  0,  0, 0, 0, 0, 0, 0, 1, 2,  2,  2,  3,  1,  3,  1,  0, 2,  3,  4]

health_coal = 1
health_copper = 2
health_gold = 2

[level_names]
# Default name uses the level number +1 
default = "Depth %d"
0  = "Into the depths"
5  = "Can you dig it?"
10 = "Dirty hands"
15 = "Loads of coal"
20 = "There be gold"

[bombs]
handlers = [
	"line", 
	"standard", 
	"escalator", 
	"exotic", 
	"fizzle", 
	"swapdirection", 
	"crossswap", 
	"delayedblast", 
	"squareswap", 
	"colorswap", 
	"oreblaster"
]
